---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# fsdac

This is a package to demonstrate the development of an R package using native 
C code generated by the MATLAB Coder. The function translated so far and included in the package are: addt(), FSR(), LXS(), FSRfan(), FSRbsb().

## Installation

You can install 'fsdac' from github with:

```{r gh-installation, eval = FALSE}
# install.packages("remotes")
remotes::install_github("UniprJRC/FSDA-MATLAB_Coder", subdir="R-package")
```

## Example

This is a basic example which shows you if the package is properly installed:

```{r example}
library(fsdac)
##  FSR with all default options =================================
    n <- 200
    p <- 3
    set.seed(123456)
    X <- matrix(rnorm(n*p), nrow=n)

##  Uncontaminated data
    y <- rnorm(n)

##  Contaminated data
    ycont <- y
    ycont[1:5] <- ycont[1:5] + 6
    (out <- FSR(ycont, X))

```
